services:
  - type: web
    name: chess-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase-connection
          property: connectionString
